services:
  server:
    image: ghcr.io/tuukezu/vihervahti:server-latest
    environment:
      - PORT=8008
    network_mode: host

  mobile:
    image: ghcr.io/tuukezu/vihervahti:mobile-latest
    network_mode: host

  cli:
    image: ghcr.io/tuukezu/vihervahti:sensor-latest
    ports:
      - 8010:80